import * as XLSX from "xlsx";

export interface SampleMedicineRow {
  "Medicine Name": string;
  "Generic / Salt Name": string;
  "Brand Name": string;
  "Medicine Type": string;
  "Category": string;
  "Sub Category": string;
  "Manufacturer": string;
  "Prescription Required": string; // "Yes" or "No"
  "Packing Count": number; // e.g. 10, 15, 20
  "Packaging Unit": string; // Sheet / Strip, Bottle, Box, Vial
  "Sheet Price": number; // Selling price per sheet
  "Per Medicine Price": number; // Selling price per tablet
  "Sheet Cost Price": number; // Purchase cost per sheet
  "Per Medicine Cost Price": number; // Purchase cost per tablet
  "Full Sheets Stock": number; // Number of sheets in stock
  "Loose Units Stock": number; // Loose tablets
  "Batch Number": string;
  "Expiry Date": string; // YYYY-MM-DD
  "Description": string;
}

// 200 Realistic Pharmacy Formulations
export const sampleMedicines200: SampleMedicineRow[] = [
  // 1-25: Pain Relief & Analgesics
  {
    "Medicine Name": "Dolo 650 Tablet",
    "Generic / Salt Name": "Paracetamol 650mg",
    "Brand Name": "Dolo",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Antipyretic & Fever",
    "Manufacturer": "Micro Labs Ltd",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 33.50,
    "Per Medicine Price": 2.23,
    "Sheet Cost Price": 24.00,
    "Per Medicine Cost Price": 1.60,
    "Full Sheets Stock": 80,
    "Loose Units Stock": 7,
    "Batch Number": "DL-650-2026",
    "Expiry Date": "2028-06-30",
    "Description": "Effective antipyretic for high fever, body pain, and headache."
  },
  {
    "Medicine Name": "Calpol 650 Tablet",
    "Generic / Salt Name": "Paracetamol 650mg",
    "Brand Name": "Calpol",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Antipyretic & Fever",
    "Manufacturer": "GlaxoSmithKline",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 34.00,
    "Per Medicine Price": 2.27,
    "Sheet Cost Price": 25.00,
    "Per Medicine Cost Price": 1.67,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 4,
    "Batch Number": "CAL-9912",
    "Expiry Date": "2027-11-30",
    "Description": "Gentle pain and fever relief for adults."
  },
  {
    "Medicine Name": "Zerodol-P Tablet",
    "Generic / Salt Name": "Aceclofenac 100mg + Paracetamol 325mg",
    "Brand Name": "Zerodol",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "NSAIDs & Joint Pain",
    "Manufacturer": "Ipca Laboratories",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 68.00,
    "Per Medicine Price": 6.80,
    "Sheet Cost Price": 51.00,
    "Per Medicine Cost Price": 5.10,
    "Full Sheets Stock": 45,
    "Loose Units Stock": 6,
    "Batch Number": "ZDP-4402",
    "Expiry Date": "2028-01-31",
    "Description": "Relief from osteoarthritis, rheumatoid arthritis, and dental ache."
  },
  {
    "Medicine Name": "Zerodol-SP Tablet",
    "Generic / Salt Name": "Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg",
    "Brand Name": "Zerodol",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Anti-Inflammatory & Swelling",
    "Manufacturer": "Ipca Laboratories",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 115.00,
    "Per Medicine Price": 11.50,
    "Sheet Cost Price": 86.00,
    "Per Medicine Cost Price": 8.60,
    "Full Sheets Stock": 60,
    "Loose Units Stock": 3,
    "Batch Number": "ZSP-8831",
    "Expiry Date": "2027-09-30",
    "Description": "Triple action pain, fever, and post-surgery inflammation reduction."
  },
  {
    "Medicine Name": "Combiflam Tablet",
    "Generic / Salt Name": "Ibuprofen 400mg + Paracetamol 325mg",
    "Brand Name": "Combiflam",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "NSAIDs & Joint Pain",
    "Manufacturer": "Sanofi India Ltd",
    "Prescription Required": "No",
    "Packing Count": 20,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 52.00,
    "Per Medicine Price": 2.60,
    "Sheet Cost Price": 38.00,
    "Per Medicine Cost Price": 1.90,
    "Full Sheets Stock": 75,
    "Loose Units Stock": 8,
    "Batch Number": "CMB-2026",
    "Expiry Date": "2028-04-30",
    "Description": "Fast relief from muscular aches, toothache, and sprains."
  },
  {
    "Medicine Name": "Voveran 50 GE Tablet",
    "Generic / Salt Name": "Diclofenac Sodium 50mg",
    "Brand Name": "Voveran",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "NSAIDs & Joint Pain",
    "Manufacturer": "Novartis India",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 95.00,
    "Per Medicine Price": 6.33,
    "Sheet Cost Price": 72.00,
    "Per Medicine Cost Price": 4.80,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 2,
    "Batch Number": "VOV-5012",
    "Expiry Date": "2027-08-31",
    "Description": "Non-steroidal anti-inflammatory for chronic joint pain and acute injury."
  },
  {
    "Medicine Name": "Meftal-Spas Tablet",
    "Generic / Salt Name": "Mefenamic Acid 250mg + Dicyclomine 10mg",
    "Brand Name": "Meftal",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Antispasmodic & Cramps",
    "Manufacturer": "Blue Cross Labs",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 53.00,
    "Per Medicine Price": 5.30,
    "Sheet Cost Price": 39.00,
    "Per Medicine Cost Price": 3.90,
    "Full Sheets Stock": 55,
    "Loose Units Stock": 5,
    "Batch Number": "MFT-911",
    "Expiry Date": "2028-03-31",
    "Description": "Relief from abdominal pain, menstrual cramps, and intestinal spasms."
  },
  {
    "Medicine Name": "Nucoxia 90 Tablet",
    "Generic / Salt Name": "Etoricoxib 90mg",
    "Brand Name": "Nucoxia",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "COX-2 Selective NSAIDs",
    "Manufacturer": "Zydus Cadila",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 240.00,
    "Per Medicine Price": 16.00,
    "Sheet Cost Price": 180.00,
    "Per Medicine Cost Price": 12.00,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 4,
    "Batch Number": "NUC-904",
    "Expiry Date": "2027-10-31",
    "Description": "Selective COX-2 inhibitor for osteoarthritis and ankylosing spondylitis."
  },
  {
    "Medicine Name": "Ultracet Tablet",
    "Generic / Salt Name": "Tramadol 37.5mg + Paracetamol 325mg",
    "Brand Name": "Ultracet",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Opioid Analgesics",
    "Manufacturer": "Janssen / J&J",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 275.00,
    "Per Medicine Price": 18.33,
    "Sheet Cost Price": 210.00,
    "Per Medicine Cost Price": 14.00,
    "Full Sheets Stock": 20,
    "Loose Units Stock": 3,
    "Batch Number": "ULT-771",
    "Expiry Date": "2027-05-31",
    "Description": "Moderate to severe acute pain relief under prescription."
  },
  {
    "Medicine Name": "Naprosyn 500 Tablet",
    "Generic / Salt Name": "Naproxen 500mg",
    "Brand Name": "Naprosyn",
    "Medicine Type": "Tablet",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "NSAIDs & Joint Pain",
    "Manufacturer": "RPG Life Sciences",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 98.00,
    "Per Medicine Price": 6.53,
    "Sheet Cost Price": 74.00,
    "Per Medicine Cost Price": 4.93,
    "Full Sheets Stock": 35,
    "Loose Units Stock": 0,
    "Batch Number": "NAP-501",
    "Expiry Date": "2028-02-28",
    "Description": "Anti-inflammatory for gout flare-ups and tendonitis."
  },
  {
    "Medicine Name": "Volini Pain Relief Gel 30g",
    "Generic / Salt Name": "Diclofenac Diethylamine + Linseed Oil + Menthol",
    "Brand Name": "Volini",
    "Medicine Type": "Gel",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Topical Pain Relief",
    "Manufacturer": "Sun Pharma",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 145.00,
    "Per Medicine Price": 145.00,
    "Sheet Cost Price": 110.00,
    "Per Medicine Cost Price": 110.00,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 0,
    "Batch Number": "VOL-30G",
    "Expiry Date": "2028-08-31",
    "Description": "Instant spray-free gel application for backache and knee stiffness."
  },
  {
    "Medicine Name": "Moov Fast Pain Relief Cream 50g",
    "Generic / Salt Name": "Oil of Wintergreen + Pudina + Nilgiri Oil",
    "Brand Name": "Moov",
    "Medicine Type": "Cream",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Topical Pain Relief",
    "Manufacturer": "Reckitt Benckiser",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 195.00,
    "Per Medicine Price": 195.00,
    "Sheet Cost Price": 150.00,
    "Per Medicine Cost Price": 150.00,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 0,
    "Batch Number": "MOV-50G",
    "Expiry Date": "2028-09-30",
    "Description": "Ayurvedic specialist pain relief cream for back and neck ache."
  },
  {
    "Medicine Name": "Dynapar AQ 1ml Injection",
    "Generic / Salt Name": "Diclofenac Sodium 75mg/ml",
    "Brand Name": "Dynapar",
    "Medicine Type": "Injection",
    "Category": "Pain Relief & Analgesics",
    "Sub Category": "Injectable NSAIDs",
    "Manufacturer": "Troikaa Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 5,
    "Packaging Unit": "Box",
    "Sheet Price": 160.00,
    "Per Medicine Price": 32.00,
    "Sheet Cost Price": 120.00,
    "Per Medicine Cost Price": 24.00,
    "Full Sheets Stock": 25,
    "Loose Units Stock": 2,
    "Batch Number": "DYN-AQ1",
    "Expiry Date": "2027-12-31",
    "Description": "Intramuscular injection for severe renal colic and post-operative pain."
  },

  // 26-55: Antibiotics & Anti-Infectives
  {
    "Medicine Name": "Augmentin 625 Duo Tablet",
    "Generic / Salt Name": "Amoxicillin 500mg + Clavulanic Acid 125mg",
    "Brand Name": "Augmentin",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Penicillin & Beta-Lactam",
    "Manufacturer": "GlaxoSmithKline",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 223.40,
    "Per Medicine Price": 22.34,
    "Sheet Cost Price": 175.00,
    "Per Medicine Cost Price": 17.50,
    "Full Sheets Stock": 65,
    "Loose Units Stock": 4,
    "Batch Number": "AUG-625-X",
    "Expiry Date": "2027-11-30",
    "Description": "Broad spectrum penicillin antibiotic for RTI, UTI, and skin infections."
  },
  {
    "Medicine Name": "Moxikind-CV 625 Tablet",
    "Generic / Salt Name": "Amoxicillin 500mg + Clavulanate Potassium 125mg",
    "Brand Name": "Moxikind",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Penicillin & Beta-Lactam",
    "Manufacturer": "Mankind Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 185.00,
    "Per Medicine Price": 18.50,
    "Sheet Cost Price": 140.00,
    "Per Medicine Cost Price": 14.00,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 2,
    "Batch Number": "MXK-625",
    "Expiry Date": "2028-02-28",
    "Description": "Affordable amoxicillin-clavulanic acid combination for bacterial infections."
  },
  {
    "Medicine Name": "Azithral 500 Tablet",
    "Generic / Salt Name": "Azithromycin 500mg",
    "Brand Name": "Azithral",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Macrolides",
    "Manufacturer": "Alembic Pharmaceuticals",
    "Prescription Required": "Yes",
    "Packing Count": 5,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 132.00,
    "Per Medicine Price": 26.40,
    "Sheet Cost Price": 100.00,
    "Per Medicine Cost Price": 20.00,
    "Full Sheets Stock": 70,
    "Loose Units Stock": 1,
    "Batch Number": "AZT-500",
    "Expiry Date": "2028-05-31",
    "Description": "Macrolide antibiotic for throat infections, pneumonia, and sinusitis."
  },
  {
    "Medicine Name": "Azee 500 Tablet",
    "Generic / Salt Name": "Azithromycin 500mg",
    "Brand Name": "Azee",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Macrolides",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 5,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 131.00,
    "Per Medicine Price": 26.20,
    "Sheet Cost Price": 99.00,
    "Per Medicine Cost Price": 19.80,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 3,
    "Batch Number": "AZ-500C",
    "Expiry Date": "2027-12-31",
    "Description": "3-day to 5-day antibiotic course for upper respiratory tract infections."
  },
  {
    "Medicine Name": "Taxim-O 200 Tablet",
    "Generic / Salt Name": "Cefixime 200mg",
    "Brand Name": "Taxim",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Cephalosporins (3rd Gen)",
    "Manufacturer": "Alkem Laboratories",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 118.00,
    "Per Medicine Price": 11.80,
    "Sheet Cost Price": 88.00,
    "Per Medicine Cost Price": 8.80,
    "Full Sheets Stock": 55,
    "Loose Units Stock": 5,
    "Batch Number": "TXM-200",
    "Expiry Date": "2028-04-30",
    "Description": "Third-generation cephalosporin for typhoid fever and bronchitis."
  },
  {
    "Medicine Name": "Zifi 200 Tablet",
    "Generic / Salt Name": "Cefixime 200mg",
    "Brand Name": "Zifi",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Cephalosporins (3rd Gen)",
    "Manufacturer": "FDC Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 116.00,
    "Per Medicine Price": 11.60,
    "Sheet Cost Price": 87.00,
    "Per Medicine Cost Price": 8.70,
    "Full Sheets Stock": 45,
    "Loose Units Stock": 2,
    "Batch Number": "ZIF-200",
    "Expiry Date": "2027-09-30",
    "Description": "Effective oral antibiotic for uncomplicated urinary tract and ear infections."
  },
  {
    "Medicine Name": "Ciplox 500 Tablet",
    "Generic / Salt Name": "Ciprofloxacin 500mg",
    "Brand Name": "Ciplox",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Fluoroquinolones",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 45.00,
    "Per Medicine Price": 4.50,
    "Sheet Cost Price": 32.00,
    "Per Medicine Cost Price": 3.20,
    "Full Sheets Stock": 60,
    "Loose Units Stock": 6,
    "Batch Number": "CPX-500",
    "Expiry Date": "2028-01-31",
    "Description": "Broad spectrum fluoroquinolone for bone, joint, and gastrointestinal infections."
  },
  {
    "Medicine Name": "O2 Tablet",
    "Generic / Salt Name": "Ofloxacin 200mg + Ornidazole 500mg",
    "Brand Name": "O2",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Fluoroquinolones & Antiprotozoal",
    "Manufacturer": "Medley Pharmaceuticals",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 155.00,
    "Per Medicine Price": 15.50,
    "Sheet Cost Price": 115.00,
    "Per Medicine Cost Price": 11.50,
    "Full Sheets Stock": 65,
    "Loose Units Stock": 7,
    "Batch Number": "O2-MDL",
    "Expiry Date": "2027-10-31",
    "Description": "First-line combination therapy for bacterial and amoebic diarrheas."
  },
  {
    "Medicine Name": "Doxy-1 L-DR Forte Capsule",
    "Generic / Salt Name": "Doxycycline 100mg + Lactic Acid Bacillus",
    "Brand Name": "Doxy-1",
    "Medicine Type": "Capsule",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Tetracyclines",
    "Manufacturer": "USV Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 110.00,
    "Per Medicine Price": 11.00,
    "Sheet Cost Price": 80.00,
    "Per Medicine Cost Price": 8.00,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 5,
    "Batch Number": "DOX-100",
    "Expiry Date": "2028-06-30",
    "Description": "Tetracycline antibiotic for acne vulgaris, cholera, and tick-borne infections."
  },
  {
    "Medicine Name": "Flagyl 400 Tablet",
    "Generic / Salt Name": "Metronidazole 400mg",
    "Brand Name": "Flagyl",
    "Medicine Type": "Tablet",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Nitroimidazoles & Antiprotozoal",
    "Manufacturer": "Abbott India",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 24.50,
    "Per Medicine Price": 1.63,
    "Sheet Cost Price": 18.00,
    "Per Medicine Cost Price": 1.20,
    "Full Sheets Stock": 90,
    "Loose Units Stock": 10,
    "Batch Number": "FLG-400",
    "Expiry Date": "2028-03-31",
    "Description": "Antiprotozoal and anaerobic antibiotic for dental and intestinal amoebiasis."
  },
  {
    "Medicine Name": "Monocef 1g Injection",
    "Generic / Salt Name": "Ceftriaxone Sodium 1000mg",
    "Brand Name": "Monocef",
    "Medicine Type": "Injection",
    "Category": "Antibiotics & Anti-Infectives",
    "Sub Category": "Cephalosporins (Injectable)",
    "Manufacturer": "Aristo Pharmaceuticals",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Vial",
    "Sheet Price": 72.00,
    "Per Medicine Price": 72.00,
    "Sheet Cost Price": 52.00,
    "Per Medicine Cost Price": 52.00,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 0,
    "Batch Number": "MCF-1G",
    "Expiry Date": "2027-08-31",
    "Description": "Potent IV/IM cephalosporin for severe hospital and bacterial infections."
  },

  // 56-85: Gastrointestinal & Antacids
  {
    "Medicine Name": "Pan 40 Tablet",
    "Generic / Salt Name": "Pantoprazole 40mg",
    "Brand Name": "Pan",
    "Medicine Type": "Tablet",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Proton Pump Inhibitors (PPI)",
    "Manufacturer": "Alkem Laboratories",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 158.00,
    "Per Medicine Price": 10.53,
    "Sheet Cost Price": 118.00,
    "Per Medicine Cost Price": 7.87,
    "Full Sheets Stock": 95,
    "Loose Units Stock": 6,
    "Batch Number": "PAN-40A",
    "Expiry Date": "2028-07-31",
    "Description": "Proton pump inhibitor for gastroesophageal reflux disease (GERD) and acidity."
  },
  {
    "Medicine Name": "Pan-D Capsule",
    "Generic / Salt Name": "Pantoprazole 40mg + Domperidone 30mg SR",
    "Brand Name": "Pan",
    "Medicine Type": "Capsule",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "PPI & Prokinetics",
    "Manufacturer": "Alkem Laboratories",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 204.00,
    "Per Medicine Price": 13.60,
    "Sheet Cost Price": 152.00,
    "Per Medicine Cost Price": 10.13,
    "Full Sheets Stock": 110,
    "Loose Units Stock": 8,
    "Batch Number": "PND-4030",
    "Expiry Date": "2028-05-31",
    "Description": "Dual relief from acidity, heartburn, gas, and nausea."
  },
  {
    "Medicine Name": "Razo 20 Tablet",
    "Generic / Salt Name": "Rabeprazole Sodium 20mg",
    "Brand Name": "Razo",
    "Medicine Type": "Tablet",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Proton Pump Inhibitors (PPI)",
    "Manufacturer": "Dr. Reddy's Labs",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 140.00,
    "Per Medicine Price": 9.33,
    "Sheet Cost Price": 105.00,
    "Per Medicine Cost Price": 7.00,
    "Full Sheets Stock": 60,
    "Loose Units Stock": 4,
    "Batch Number": "RZO-20R",
    "Expiry Date": "2028-01-31",
    "Description": "Rapid acting rabeprazole for hyperacidity and peptic ulcer healing."
  },
  {
    "Medicine Name": "Rablet-D Capsule",
    "Generic / Salt Name": "Rabeprazole 20mg + Domperidone 30mg SR",
    "Brand Name": "Rablet",
    "Medicine Type": "Capsule",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "PPI & Prokinetics",
    "Manufacturer": "Lupin Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 190.00,
    "Per Medicine Price": 19.00,
    "Sheet Cost Price": 142.00,
    "Per Medicine Cost Price": 14.20,
    "Full Sheets Stock": 45,
    "Loose Units Stock": 3,
    "Batch Number": "RBL-D10",
    "Expiry Date": "2027-11-30",
    "Description": "Controls acid regurgitation, fullness, and bloating."
  },
  {
    "Medicine Name": "Omez 20 Capsule",
    "Generic / Salt Name": "Omeprazole 20mg",
    "Brand Name": "Omez",
    "Medicine Type": "Capsule",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Proton Pump Inhibitors (PPI)",
    "Manufacturer": "Dr. Reddy's Labs",
    "Prescription Required": "No",
    "Packing Count": 20,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 115.00,
    "Per Medicine Price": 5.75,
    "Sheet Cost Price": 85.00,
    "Per Medicine Cost Price": 4.25,
    "Full Sheets Stock": 75,
    "Loose Units Stock": 9,
    "Batch Number": "OMZ-20",
    "Expiry Date": "2028-03-31",
    "Description": "Classic proton pump inhibitor for daily acid indigestion."
  },
  {
    "Medicine Name": "Sucrafil O Gel 200ml",
    "Generic / Salt Name": "Sucralfate 1000mg + Oxetacaine 20mg / 10ml",
    "Brand Name": "Sucrafil",
    "Medicine Type": "Syrup",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Mucosal Protectants & Antacids",
    "Manufacturer": "Fourrts Laboratories",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 275.00,
    "Per Medicine Price": 275.00,
    "Sheet Cost Price": 210.00,
    "Per Medicine Cost Price": 210.00,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 0,
    "Batch Number": "SCF-200M",
    "Expiry Date": "2027-10-31",
    "Description": "Mucosal barrier coating suspension for immediate ulcer pain relief."
  },
  {
    "Medicine Name": "Emeset 4mg Tablet",
    "Generic / Salt Name": "Ondansetron 4mg",
    "Brand Name": "Emeset",
    "Medicine Type": "Tablet",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Antiemetics & Nausea",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 56.00,
    "Per Medicine Price": 5.60,
    "Sheet Cost Price": 40.00,
    "Per Medicine Cost Price": 4.00,
    "Full Sheets Stock": 65,
    "Loose Units Stock": 5,
    "Batch Number": "EMT-4MG",
    "Expiry Date": "2028-04-30",
    "Description": "Fast relief from vomiting, nausea, and motion sickness."
  },
  {
    "Medicine Name": "Duphalac Oral Solution 200ml",
    "Generic / Salt Name": "Lactulose 3.335g/5ml",
    "Brand Name": "Duphalac",
    "Medicine Type": "Syrup",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Laxatives & Constipation",
    "Manufacturer": "Abbott India",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 345.00,
    "Per Medicine Price": 345.00,
    "Sheet Cost Price": 265.00,
    "Per Medicine Cost Price": 265.00,
    "Full Sheets Stock": 35,
    "Loose Units Stock": 0,
    "Batch Number": "DPH-200",
    "Expiry Date": "2027-12-31",
    "Description": "Osmotic prebiotic laxative for gentle chronic constipation relief."
  },
  {
    "Medicine Name": "Imodium 2mg Capsule",
    "Generic / Salt Name": "Loperamide Hydrochloride 2mg",
    "Brand Name": "Imodium",
    "Medicine Type": "Capsule",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Antidiarrheal",
    "Manufacturer": "Johnson & Johnson",
    "Prescription Required": "No",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 30.00,
    "Per Medicine Price": 3.00,
    "Sheet Cost Price": 22.00,
    "Per Medicine Cost Price": 2.20,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 4,
    "Batch Number": "IMD-2MG",
    "Expiry Date": "2028-06-30",
    "Description": "Slows intestinal motility for acute non-infectious loose motions."
  },
  {
    "Medicine Name": "Digene Mint Flavour Liquid 200ml",
    "Generic / Salt Name": "Magnesium Hydroxide + Aluminium Hydroxide + Simethicone",
    "Brand Name": "Digene",
    "Medicine Type": "Syrup",
    "Category": "Gastrointestinal & Antacids",
    "Sub Category": "Antacids & Gas Relief",
    "Manufacturer": "Abbott India",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 160.00,
    "Per Medicine Price": 160.00,
    "Sheet Cost Price": 122.00,
    "Per Medicine Cost Price": 122.00,
    "Full Sheets Stock": 45,
    "Loose Units Stock": 0,
    "Batch Number": "DGN-200",
    "Expiry Date": "2028-09-30",
    "Description": "Neutralizes stomach acid and relieves burning sensation."
  },

  // 86-115: Cardiovascular & Hypertension
  {
    "Medicine Name": "Telma 40 Tablet",
    "Generic / Salt Name": "Telmisartan 40mg",
    "Brand Name": "Telma",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Angiotensin Receptor Blockers (ARB)",
    "Manufacturer": "Glenmark Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 30,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 290.00,
    "Per Medicine Price": 9.67,
    "Sheet Cost Price": 220.00,
    "Per Medicine Cost Price": 7.33,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 12,
    "Batch Number": "TLM-4030",
    "Expiry Date": "2028-08-31",
    "Description": "Long-acting ARB for daily high blood pressure management and cardio protection."
  },
  {
    "Medicine Name": "Telma-AM Tablet",
    "Generic / Salt Name": "Telmisartan 40mg + Amlodipine 5mg",
    "Brand Name": "Telma",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "ARB + Calcium Channel Blocker",
    "Manufacturer": "Glenmark Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 235.00,
    "Per Medicine Price": 15.67,
    "Sheet Cost Price": 178.00,
    "Per Medicine Cost Price": 11.87,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 5,
    "Batch Number": "TAM-405",
    "Expiry Date": "2027-12-31",
    "Description": "Combination antihypertensive for uncontrolled essential hypertension."
  },
  {
    "Medicine Name": "Amlong 5 Tablet",
    "Generic / Salt Name": "Amlodipine Besylate 5mg",
    "Brand Name": "Amlong",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Calcium Channel Blockers",
    "Manufacturer": "Micro Labs Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 75.00,
    "Per Medicine Price": 5.00,
    "Sheet Cost Price": 54.00,
    "Per Medicine Cost Price": 3.60,
    "Full Sheets Stock": 80,
    "Loose Units Stock": 7,
    "Batch Number": "AML-5M",
    "Expiry Date": "2028-05-31",
    "Description": "Relaxes blood vessels and reduces peripheral resistance."
  },
  {
    "Medicine Name": "Atorva 20 Tablet",
    "Generic / Salt Name": "Atorvastatin Calcium 20mg",
    "Brand Name": "Atorva",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Cholesterol & Statins",
    "Manufacturer": "Zydus Cadila",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 265.00,
    "Per Medicine Price": 17.67,
    "Sheet Cost Price": 200.00,
    "Per Medicine Cost Price": 13.33,
    "Full Sheets Stock": 45,
    "Loose Units Stock": 4,
    "Batch Number": "ATV-20Z",
    "Expiry Date": "2028-03-31",
    "Description": "Lowers bad cholesterol (LDL) and triglycerides, reduces heart attack risk."
  },
  {
    "Medicine Name": "Rosuvas 10 Tablet",
    "Generic / Salt Name": "Rosuvastatin 10mg",
    "Brand Name": "Rosuvas",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Cholesterol & Statins",
    "Manufacturer": "Sun Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 280.00,
    "Per Medicine Price": 18.67,
    "Sheet Cost Price": 210.00,
    "Per Medicine Cost Price": 14.00,
    "Full Sheets Stock": 55,
    "Loose Units Stock": 3,
    "Batch Number": "RSV-10S",
    "Expiry Date": "2028-06-30",
    "Description": "High potency HMG-CoA reductase inhibitor for dyslipidemia."
  },
  {
    "Medicine Name": "Betaloc 25 Tablet",
    "Generic / Salt Name": "Metoprolol Succinate 25mg ER",
    "Brand Name": "Betaloc",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Beta Blockers",
    "Manufacturer": "AstraZeneca",
    "Prescription Required": "Yes",
    "Packing Count": 20,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 195.00,
    "Per Medicine Price": 9.75,
    "Sheet Cost Price": 148.00,
    "Per Medicine Cost Price": 7.40,
    "Full Sheets Stock": 35,
    "Loose Units Stock": 6,
    "Batch Number": "BTL-25",
    "Expiry Date": "2027-11-30",
    "Description": "Cardioselective beta blocker for angina pectoris and heart rate stabilization."
  },
  {
    "Medicine Name": "Ecosprin 75 Tablet",
    "Generic / Salt Name": "Aspirin 75mg Gastro-resistant",
    "Brand Name": "Ecosprin",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Blood Thinners & Antiplatelets",
    "Manufacturer": "USV Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 14,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 6.80,
    "Per Medicine Price": 0.49,
    "Sheet Cost Price": 4.90,
    "Per Medicine Cost Price": 0.35,
    "Full Sheets Stock": 120,
    "Loose Units Stock": 5,
    "Batch Number": "ECO-75",
    "Expiry Date": "2028-10-31",
    "Description": "Low-dose antiplatelet prevention against blood clots and stroke."
  },
  {
    "Medicine Name": "Clopilet 75 Tablet",
    "Generic / Salt Name": "Clopidogrel Bisulfate 75mg",
    "Brand Name": "Clopilet",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Blood Thinners & Antiplatelets",
    "Manufacturer": "Sun Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 135.00,
    "Per Medicine Price": 9.00,
    "Sheet Cost Price": 102.00,
    "Per Medicine Cost Price": 6.80,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 2,
    "Batch Number": "CLP-75",
    "Expiry Date": "2028-02-28",
    "Description": "Prevents coronary stent thrombosis and secondary ischemic events."
  },
  {
    "Medicine Name": "Concor 5 Tablet",
    "Generic / Salt Name": "Bisoprolol Fumarate 5mg",
    "Brand Name": "Concor",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "Beta Blockers",
    "Manufacturer": "Merck Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 112.00,
    "Per Medicine Price": 11.20,
    "Sheet Cost Price": 85.00,
    "Per Medicine Cost Price": 8.50,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 1,
    "Batch Number": "CNC-5MG",
    "Expiry Date": "2027-10-31",
    "Description": "Treatment of stable chronic heart failure and arterial hypertension."
  },
  {
    "Medicine Name": "Cardace 2.5 Tablet",
    "Generic / Salt Name": "Ramipril 2.5mg",
    "Brand Name": "Cardace",
    "Medicine Type": "Tablet",
    "Category": "Cardiovascular & Hypertension",
    "Sub Category": "ACE Inhibitors",
    "Manufacturer": "Sanofi India",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 145.00,
    "Per Medicine Price": 9.67,
    "Sheet Cost Price": 110.00,
    "Per Medicine Cost Price": 7.33,
    "Full Sheets Stock": 25,
    "Loose Units Stock": 3,
    "Batch Number": "CDC-25",
    "Expiry Date": "2028-04-30",
    "Description": "ACE inhibitor to delay diabetic nephropathy and reduce heart risk."
  },

  // 116-140: Anti-Diabetic Care
  {
    "Medicine Name": "Glycomet 500 SR Tablet",
    "Generic / Salt Name": "Metformin Hydrochloride 500mg SR",
    "Brand Name": "Glycomet",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "Biguanides",
    "Manufacturer": "USV Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 20,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 48.00,
    "Per Medicine Price": 2.40,
    "Sheet Cost Price": 35.00,
    "Per Medicine Cost Price": 1.75,
    "Full Sheets Stock": 90,
    "Loose Units Stock": 11,
    "Batch Number": "GLY-500",
    "Expiry Date": "2028-09-30",
    "Description": "Standard foundation therapy for Type-2 Diabetes Mellitus."
  },
  {
    "Medicine Name": "Glycomet GP 1 Tablet",
    "Generic / Salt Name": "Glimepiride 1mg + Metformin 500mg SR",
    "Brand Name": "Glycomet GP",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "Sulfonylurea & Biguanide",
    "Manufacturer": "USV Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 125.00,
    "Per Medicine Price": 8.33,
    "Sheet Cost Price": 94.00,
    "Per Medicine Cost Price": 6.27,
    "Full Sheets Stock": 70,
    "Loose Units Stock": 6,
    "Batch Number": "GGP-1M",
    "Expiry Date": "2028-07-31",
    "Description": "Dual hypoglycemic action for post-prandial and fasting sugar control."
  },
  {
    "Medicine Name": "Amaryl 2mg Tablet",
    "Generic / Salt Name": "Glimepiride 2mg",
    "Brand Name": "Amaryl",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "Sulfonylureas",
    "Manufacturer": "Sanofi India",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 178.00,
    "Per Medicine Price": 11.87,
    "Sheet Cost Price": 134.00,
    "Per Medicine Cost Price": 8.93,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 4,
    "Batch Number": "AMR-2MG",
    "Expiry Date": "2028-01-31",
    "Description": "Stimulates pancreatic beta-cells to secrete insulin."
  },
  {
    "Medicine Name": "Januvia 100mg Tablet",
    "Generic / Salt Name": "Sitagliptin 100mg",
    "Brand Name": "Januvia",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "DPP-4 Inhibitors",
    "Manufacturer": "MSD Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 14,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 560.00,
    "Per Medicine Price": 40.00,
    "Sheet Cost Price": 430.00,
    "Per Medicine Cost Price": 30.71,
    "Full Sheets Stock": 25,
    "Loose Units Stock": 2,
    "Batch Number": "JNV-100",
    "Expiry Date": "2027-12-31",
    "Description": "Weight-neutral DPP-4 inhibitor without risk of sudden hypoglycemia."
  },
  {
    "Medicine Name": "Forxiga 10mg Tablet",
    "Generic / Salt Name": "Dapagliflozin 10mg",
    "Brand Name": "Forxiga",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "SGLT2 Inhibitors",
    "Manufacturer": "AstraZeneca",
    "Prescription Required": "Yes",
    "Packing Count": 14,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 795.00,
    "Per Medicine Price": 56.79,
    "Sheet Cost Price": 610.00,
    "Per Medicine Cost Price": 43.57,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 3,
    "Batch Number": "FRX-10",
    "Expiry Date": "2028-05-31",
    "Description": "SGLT2 inhibitor expelling excess glucose via renal pathway; heart-safe."
  },
  {
    "Medicine Name": "Jardiance 10mg Tablet",
    "Generic / Salt Name": "Empagliflozin 10mg",
    "Brand Name": "Jardiance",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "SGLT2 Inhibitors",
    "Manufacturer": "Boehringer Ingelheim",
    "Prescription Required": "Yes",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 550.00,
    "Per Medicine Price": 55.00,
    "Sheet Cost Price": 420.00,
    "Per Medicine Cost Price": 42.00,
    "Full Sheets Stock": 20,
    "Loose Units Stock": 1,
    "Batch Number": "JRD-10",
    "Expiry Date": "2027-11-30",
    "Description": "Cardiovascular risk-reducing SGLT2 inhibitor for diabetics."
  },
  {
    "Medicine Name": "Tenalim 20mg Tablet",
    "Generic / Salt Name": "Teneligliptin Hydrobromide 20mg",
    "Brand Name": "Tenalim",
    "Medicine Type": "Tablet",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "DPP-4 Inhibitors",
    "Manufacturer": "Torrent Pharmaceuticals",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 145.00,
    "Per Medicine Price": 9.67,
    "Sheet Cost Price": 110.00,
    "Per Medicine Cost Price": 7.33,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 5,
    "Batch Number": "TNL-20",
    "Expiry Date": "2028-03-31",
    "Description": "Economical DPP-4 inhibitor safe in mild to moderate kidney impairment."
  },
  {
    "Medicine Name": "Lantus 100IU/ml Cartridge 3ml",
    "Generic / Salt Name": "Insulin Glargine 100 IU/ml",
    "Brand Name": "Lantus",
    "Medicine Type": "Injection",
    "Category": "Anti-Diabetic Care",
    "Sub Category": "Basal Insulin Analogues",
    "Manufacturer": "Sanofi India",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Vial",
    "Sheet Price": 710.00,
    "Per Medicine Price": 710.00,
    "Sheet Cost Price": 560.00,
    "Per Medicine Cost Price": 560.00,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 0,
    "Batch Number": "LNT-3ML",
    "Expiry Date": "2027-09-30",
    "Description": "24-hour peakless basal insulin cartridge for pen devices."
  },

  // 141-165: Respiratory, Cough & Allergy
  {
    "Medicine Name": "Montair-LC Tablet",
    "Generic / Salt Name": "Montelukast 10mg + Levocetirizine 5mg",
    "Brand Name": "Montair",
    "Medicine Type": "Tablet",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Anti-Allergic & Asthma",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 270.00,
    "Per Medicine Price": 18.00,
    "Sheet Cost Price": 205.00,
    "Per Medicine Cost Price": 13.67,
    "Full Sheets Stock": 85,
    "Loose Units Stock": 7,
    "Batch Number": "MNT-LC15",
    "Expiry Date": "2028-06-30",
    "Description": "Leukotriene receptor antagonist + antihistamine for allergic rhinitis."
  },
  {
    "Medicine Name": "Levocet 5 Tablet",
    "Generic / Salt Name": "Levocetirizine Dihydrochloride 5mg",
    "Brand Name": "Levocet",
    "Medicine Type": "Tablet",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Antihistamines (2nd Gen)",
    "Manufacturer": "Hetero Healthcare",
    "Prescription Required": "No",
    "Packing Count": 10,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 55.00,
    "Per Medicine Price": 5.50,
    "Sheet Cost Price": 40.00,
    "Per Medicine Cost Price": 4.00,
    "Full Sheets Stock": 95,
    "Loose Units Stock": 9,
    "Batch Number": "LVC-5MG",
    "Expiry Date": "2028-08-31",
    "Description": "Non-sedating antihistamine for sneezing, runny nose, and hives."
  },
  {
    "Medicine Name": "Cetzine 10 Tablet",
    "Generic / Salt Name": "Cetirizine Hydrochloride 10mg",
    "Brand Name": "Cetzine",
    "Medicine Type": "Tablet",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Antihistamines (2nd Gen)",
    "Manufacturer": "Dr. Reddy's Labs",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 42.00,
    "Per Medicine Price": 2.80,
    "Sheet Cost Price": 30.00,
    "Per Medicine Cost Price": 2.00,
    "Full Sheets Stock": 80,
    "Loose Units Stock": 5,
    "Batch Number": "CTZ-10R",
    "Expiry Date": "2028-04-30",
    "Description": "Popular allergy tablet for environmental irritants and skin itch."
  },
  {
    "Medicine Name": "Ascoril LS Syrup 100ml",
    "Generic / Salt Name": "Ambroxol 30mg + Levosalbutamol 1mg + Guaifenesin 50mg / 5ml",
    "Brand Name": "Ascoril",
    "Medicine Type": "Syrup",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Bronchodilators & Expectorants",
    "Manufacturer": "Glenmark Pharma",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 128.00,
    "Per Medicine Price": 128.00,
    "Sheet Cost Price": 96.00,
    "Per Medicine Cost Price": 96.00,
    "Full Sheets Stock": 60,
    "Loose Units Stock": 0,
    "Batch Number": "ASC-LS1",
    "Expiry Date": "2027-12-31",
    "Description": "Expectorant and bronchodilator for wet chesty productive cough."
  },
  {
    "Medicine Name": "Ascoril D Plus Syrup 100ml",
    "Generic / Salt Name": "Dextromethorphan 10mg + Chlorpheniramine 2mg + Phenylephrine 5mg",
    "Brand Name": "Ascoril",
    "Medicine Type": "Syrup",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Cough Suppressants & Decongestants",
    "Manufacturer": "Glenmark Pharma",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 135.00,
    "Per Medicine Price": 135.00,
    "Sheet Cost Price": 102.00,
    "Per Medicine Cost Price": 102.00,
    "Full Sheets Stock": 50,
    "Loose Units Stock": 0,
    "Batch Number": "ASC-DPL",
    "Expiry Date": "2028-02-28",
    "Description": "Sugar-free dry cough syrup soothing tickling throat irritation."
  },
  {
    "Medicine Name": "Asthalin 100mcg Inhaler 200 MDI",
    "Generic / Salt Name": "Salbutamol 100mcg / actuation",
    "Brand Name": "Asthalin",
    "Medicine Type": "Inhaler",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Short-Acting Beta Agonists (SABA)",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Inhaler",
    "Sheet Price": 175.00,
    "Per Medicine Price": 175.00,
    "Sheet Cost Price": 132.00,
    "Per Medicine Cost Price": 132.00,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 0,
    "Batch Number": "AST-100I",
    "Expiry Date": "2028-07-31",
    "Description": "Fast-acting rescue inhaler for acute asthma bronchospasm."
  },
  {
    "Medicine Name": "Foracort 200 Rotacaps 30s",
    "Generic / Salt Name": "Budesonide 200mcg + Formoterol Fumarate 6mcg",
    "Brand Name": "Foracort",
    "Medicine Type": "Capsule",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Inhaled Corticosteroid & LABA",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 30,
    "Packaging Unit": "Bottle",
    "Sheet Price": 310.00,
    "Per Medicine Price": 10.33,
    "Sheet Cost Price": 235.00,
    "Per Medicine Cost Price": 7.83,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 0,
    "Batch Number": "FRC-200R",
    "Expiry Date": "2028-05-31",
    "Description": "Daily maintenance controller for asthma and chronic COPD symptoms."
  },
  {
    "Medicine Name": "Flomist Nasal Spray 100 MDI",
    "Generic / Salt Name": "Fluticasone Propionate 50mcg / spray",
    "Brand Name": "Flomist",
    "Medicine Type": "Drops",
    "Category": "Respiratory & Allergy",
    "Sub Category": "Nasal Corticosteroids",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 395.00,
    "Per Medicine Price": 395.00,
    "Sheet Cost Price": 298.00,
    "Per Medicine Cost Price": 298.00,
    "Full Sheets Stock": 25,
    "Loose Units Stock": 0,
    "Batch Number": "FLM-100",
    "Expiry Date": "2027-11-30",
    "Description": "Topical steroid nasal spray for persistent allergic rhinitis."
  },

  // 166-185: Dermatology & Skin Care
  {
    "Medicine Name": "Candid 1% Cream 30g",
    "Generic / Salt Name": "Clotrimazole 1% w/w",
    "Brand Name": "Candid",
    "Medicine Type": "Cream",
    "Category": "Dermatology & Skin Care",
    "Sub Category": "Topical Antifungals",
    "Manufacturer": "Glenmark Pharma",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 125.00,
    "Per Medicine Price": 125.00,
    "Sheet Cost Price": 95.00,
    "Per Medicine Cost Price": 95.00,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 0,
    "Batch Number": "CND-30G",
    "Expiry Date": "2028-06-30",
    "Description": "Broad spectrum antifungal cream for ringworm, jock itch, and athlete's foot."
  },
  {
    "Medicine Name": "Nizral 2% Cream 30g",
    "Generic / Salt Name": "Ketoconazole 2% w/w",
    "Brand Name": "Nizral",
    "Medicine Type": "Cream",
    "Category": "Dermatology & Skin Care",
    "Sub Category": "Topical Antifungals",
    "Manufacturer": "Janssen / J&J",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 285.00,
    "Per Medicine Price": 285.00,
    "Sheet Cost Price": 215.00,
    "Per Medicine Cost Price": 215.00,
    "Full Sheets Stock": 25,
    "Loose Units Stock": 0,
    "Batch Number": "NZR-2C",
    "Expiry Date": "2027-12-31",
    "Description": "Deep penetrating antifungal for stubborn tinea and fungal skin patches."
  },
  {
    "Medicine Name": "T-Bact 2% Ointment 15g",
    "Generic / Salt Name": "Mupirocin 2% w/w",
    "Brand Name": "T-Bact",
    "Medicine Type": "Ointment",
    "Category": "Dermatology & Skin Care",
    "Sub Category": "Topical Antibacterials",
    "Manufacturer": "GlaxoSmithKline",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 198.00,
    "Per Medicine Price": 198.00,
    "Sheet Cost Price": 150.00,
    "Per Medicine Cost Price": 150.00,
    "Full Sheets Stock": 35,
    "Loose Units Stock": 0,
    "Batch Number": "TB-15G",
    "Expiry Date": "2028-03-31",
    "Description": "Topical antibiotic for impetigo, infected cuts, and minor burns."
  },
  {
    "Medicine Name": "Betnovate-N Cream 20g",
    "Generic / Salt Name": "Betamethasone Valerate 0.1% + Neomycin 0.5%",
    "Brand Name": "Betnovate",
    "Medicine Type": "Cream",
    "Category": "Dermatology & Skin Care",
    "Sub Category": "Corticosteroid & Antibacterial",
    "Manufacturer": "GlaxoSmithKline",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 62.00,
    "Per Medicine Price": 62.00,
    "Sheet Cost Price": 48.00,
    "Per Medicine Cost Price": 48.00,
    "Full Sheets Stock": 55,
    "Loose Units Stock": 0,
    "Batch Number": "BTN-20N",
    "Expiry Date": "2028-09-30",
    "Description": "Anti-inflammatory steroid cream for eczema and infected skin dermatitis."
  },
  {
    "Medicine Name": "Tenovate Cream 15g",
    "Generic / Salt Name": "Clobetasol Propionate 0.05%",
    "Brand Name": "Tenovate",
    "Medicine Type": "Cream",
    "Category": "Dermatology & Skin Care",
    "Sub Category": "Super-Potent Corticosteroids",
    "Manufacturer": "GlaxoSmithKline",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Tube",
    "Sheet Price": 145.00,
    "Per Medicine Price": 145.00,
    "Sheet Cost Price": 110.00,
    "Per Medicine Cost Price": 110.00,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 0,
    "Batch Number": "TNV-15",
    "Expiry Date": "2028-01-31",
    "Description": "Ultra-potent corticosteroid for severe plaque psoriasis and lichen planus."
  },

  // 186-200: Vitamins, Minerals & Eye Drops
  {
    "Medicine Name": "Calcirol 60000 IU Sachet 1g",
    "Generic / Salt Name": "Cholecalciferol 60,000 IU (Vitamin D3)",
    "Brand Name": "Calcirol",
    "Medicine Type": "Powder",
    "Category": "Vitamins & Supplements",
    "Sub Category": "Vitamin D3 & Bone Health",
    "Manufacturer": "Cadila Pharma",
    "Prescription Required": "No",
    "Packing Count": 8,
    "Packaging Unit": "Box",
    "Sheet Price": 360.00,
    "Per Medicine Price": 45.00,
    "Sheet Cost Price": 270.00,
    "Per Medicine Cost Price": 33.75,
    "Full Sheets Stock": 60,
    "Loose Units Stock": 5,
    "Batch Number": "CLR-60K",
    "Expiry Date": "2028-11-30",
    "Description": "Weekly oral sachet granules for rapid treatment of Vitamin D deficiency."
  },
  {
    "Medicine Name": "Shelcal 500 Tablet",
    "Generic / Salt Name": "Calcium Carbonate 1250mg (Eq 500mg) + Vitamin D3 250 IU",
    "Brand Name": "Shelcal",
    "Medicine Type": "Tablet",
    "Category": "Vitamins & Supplements",
    "Sub Category": "Calcium & Bone Health",
    "Manufacturer": "Torrent Pharmaceuticals",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 138.00,
    "Per Medicine Price": 9.20,
    "Sheet Cost Price": 104.00,
    "Per Medicine Cost Price": 6.93,
    "Full Sheets Stock": 90,
    "Loose Units Stock": 8,
    "Batch Number": "SHL-500",
    "Expiry Date": "2028-07-31",
    "Description": "Essential daily calcium supplement for bone density in adults and pregnancy."
  },
  {
    "Medicine Name": "Neurobion Forte Tablet",
    "Generic / Salt Name": "Vitamin B Complex with B12",
    "Brand Name": "Neurobion",
    "Medicine Type": "Tablet",
    "Category": "Vitamins & Supplements",
    "Sub Category": "Vitamin B Complex",
    "Manufacturer": "Procter & Gamble",
    "Prescription Required": "No",
    "Packing Count": 30,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 42.00,
    "Per Medicine Price": 1.40,
    "Sheet Cost Price": 31.00,
    "Per Medicine Cost Price": 1.03,
    "Full Sheets Stock": 110,
    "Loose Units Stock": 14,
    "Batch Number": "NRB-30S",
    "Expiry Date": "2028-09-30",
    "Description": "Nerve nutrition tablet for peripheral neuropathy, tingling, and numbness."
  },
  {
    "Medicine Name": "Limcee 500mg Chewable Tablet",
    "Generic / Salt Name": "Ascorbic Acid (Vitamin C) 500mg Orange Flavour",
    "Brand Name": "Limcee",
    "Medicine Type": "Tablet",
    "Category": "Vitamins & Supplements",
    "Sub Category": "Antioxidants & Immunity",
    "Manufacturer": "Abbott India",
    "Prescription Required": "No",
    "Packing Count": 15,
    "Packaging Unit": "Sheet / Strip",
    "Sheet Price": 27.50,
    "Per Medicine Price": 1.83,
    "Sheet Cost Price": 20.00,
    "Per Medicine Cost Price": 1.33,
    "Full Sheets Stock": 100,
    "Loose Units Stock": 6,
    "Batch Number": "LMC-500",
    "Expiry Date": "2028-08-31",
    "Description": "Immunity booster chewable tablet for wound healing and antioxidant defense."
  },
  {
    "Medicine Name": "Refresh Tears Eye Drops 10ml",
    "Generic / Salt Name": "Carboxymethylcellulose Sodium 0.5%",
    "Brand Name": "Refresh",
    "Medicine Type": "Drops",
    "Category": "Ophthalmic & ENT Care",
    "Sub Category": "Lubricating Eye Drops",
    "Manufacturer": "Allergan India",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 185.00,
    "Per Medicine Price": 185.00,
    "Sheet Cost Price": 140.00,
    "Per Medicine Cost Price": 140.00,
    "Full Sheets Stock": 40,
    "Loose Units Stock": 0,
    "Batch Number": "REF-10ML",
    "Expiry Date": "2028-04-30",
    "Description": "Lubricating artificial tears for screen eye strain, dryness, and irritation."
  },
  {
    "Medicine Name": "Moxicip Eye Drops 5ml",
    "Generic / Salt Name": "Moxifloxacin 0.5% w/v",
    "Brand Name": "Moxicip",
    "Medicine Type": "Drops",
    "Category": "Ophthalmic & ENT Care",
    "Sub Category": "Ophthalmic Antibacterials",
    "Manufacturer": "Cipla Ltd",
    "Prescription Required": "Yes",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 165.00,
    "Per Medicine Price": 165.00,
    "Sheet Cost Price": 125.00,
    "Per Medicine Cost Price": 125.00,
    "Full Sheets Stock": 30,
    "Loose Units Stock": 0,
    "Batch Number": "MXC-5ML",
    "Expiry Date": "2027-12-31",
    "Description": "Antibiotic eye drops for bacterial conjunctivitis and post-cataract care."
  },
  {
    "Medicine Name": "Otrivin Adult Nasal Drops 10ml",
    "Generic / Salt Name": "Xylometazoline Hydrochloride 0.1%",
    "Brand Name": "Otrivin",
    "Medicine Type": "Drops",
    "Category": "Ophthalmic & ENT Care",
    "Sub Category": "Nasal Decongestants",
    "Manufacturer": "GlaxoSmithKline",
    "Prescription Required": "No",
    "Packing Count": 1,
    "Packaging Unit": "Bottle",
    "Sheet Price": 110.00,
    "Per Medicine Price": 110.00,
    "Sheet Cost Price": 82.00,
    "Per Medicine Cost Price": 82.00,
    "Full Sheets Stock": 45,
    "Loose Units Stock": 0,
    "Batch Number": "OTR-10ML",
    "Expiry Date": "2028-06-30",
    "Description": "Fast 25-second action nasal decongestant for blocked nose from cold and allergy."
  }
];

// Helper to expand the template to 200 items programmatically
export function getFull200MedicinesSample(): SampleMedicineRow[] {
  const result: SampleMedicineRow[] = [...sampleMedicines200];
  
  const variations = [
    { name: "500mg", type: "Tablet", count: 10, unit: "Sheet / Strip", sheetP: 45, unitP: 4.5, sheetC: 32, unitC: 3.2 },
    { name: "250mg", type: "Capsule", count: 10, unit: "Sheet / Strip", sheetP: 65, unitP: 6.5, sheetC: 48, unitC: 4.8 },
    { name: "Forte", type: "Tablet", count: 15, unit: "Sheet / Strip", sheetP: 110, unitP: 7.33, sheetC: 80, unitC: 5.33 },
    { name: "Suspension 60ml", type: "Syrup", count: 1, unit: "Bottle", sheetP: 85, unitP: 85, sheetC: 62, unitC: 62 },
    { name: "Injection 2ml", type: "Injection", count: 5, unit: "Box", sheetP: 150, unitP: 30, sheetC: 110, unitC: 22 },
  ];

  const saltBases = [
    { name: "Amikacin 500mg Injection", salt: "Amikacin Sulfate 500mg/2ml", brand: "Mikacin", cat: "Antibiotics & Anti-Infectives", sub: "Aminoglycosides", mfg: "Aristo Pharma", rx: "Yes", type: "Injection", count: 1, unit: "Vial", p: 95 },
    { name: "Linezolid 600mg Tablet", salt: "Linezolid 600mg", brand: "Lizomac", cat: "Antibiotics & Anti-Infectives", sub: "Oxazolidinones", mfg: "Macleods Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 380 },
    { name: "Clindamycin 300mg Capsule", salt: "Clindamycin Hydrochloride 300mg", brand: "Dalacin C", cat: "Antibiotics & Anti-Infectives", sub: "Lincosamides", mfg: "Pfizer India", rx: "Yes", type: "Capsule", count: 10, unit: "Sheet / Strip", p: 290 },
    { name: "Fluconazole 150mg Tablet", salt: "Fluconazole 150mg", brand: "Forcan 150", cat: "Antibiotics & Anti-Infectives", sub: "Triazole Antifungals", mfg: "Cipla Ltd", rx: "Yes", type: "Tablet", count: 3, unit: "Sheet / Strip", p: 42 },
    { name: "Itraconazole 200mg Capsule", salt: "Itraconazole 200mg Pellets", brand: "Candiforce 200", cat: "Antibiotics & Anti-Infectives", sub: "Triazole Antifungals", mfg: "Mankind Pharma", rx: "Yes", type: "Capsule", count: 10, unit: "Sheet / Strip", p: 220 },
    { name: "Albendazole 400mg Tablet", salt: "Albendazole 400mg", brand: "Zentel 400", cat: "Antibiotics & Anti-Infectives", sub: "Anthelmintics & Deworming", mfg: "GlaxoSmithKline", rx: "No", type: "Tablet", count: 1, unit: "Sheet / Strip", p: 18 },
    { name: "Drotaverine 80mg Tablet", salt: "Drotaverine Hydrochloride 80mg", brand: "Drotin-DS", cat: "Pain Relief & Analgesics", sub: "Smooth Muscle Antispasmodics", mfg: "Walter Bushnell", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 195 },
    { name: "Lornoxicam 8mg Tablet", salt: "Lornoxicam 8mg", brand: "Lornoxi 8", cat: "Pain Relief & Analgesics", sub: "Oxicam NSAIDs", mfg: "Sun Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 95 },
    { name: "Chymoral Forte Tablet", salt: "Trypsin + Chymotrypsin 100,000 AU", brand: "Chymoral", cat: "Pain Relief & Analgesics", sub: "Enzymatic Anti-Inflammatory", mfg: "Torrent Pharma", rx: "Yes", type: "Tablet", count: 20, unit: "Sheet / Strip", p: 480 },
    { name: "Esomac 40 Tablet", salt: "Esomeprazole Magnesium 40mg", brand: "Esomac", cat: "Gastrointestinal & Antacids", sub: "Proton Pump Inhibitors (PPI)", mfg: "Cipla Ltd", rx: "No", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 175 },
    { name: "Ilaprazole 10mg Tablet", salt: "Ilaprazole 10mg", brand: "Ilapro 10", cat: "Gastrointestinal & Antacids", sub: "Proton Pump Inhibitors (PPI)", mfg: "Ajanta Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 140 },
    { name: "Ursodeoxycholic Acid 300mg", salt: "Ursodeoxycholic Acid 300mg", brand: "Udiliv 300", cat: "Gastrointestinal & Antacids", sub: "Hepatoprotective & Bile Acids", mfg: "Abbott India", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 580 },
    { name: "Rifaximin 400mg Tablet", salt: "Rifaximin 400mg", brand: "Rifagut 400", cat: "Gastrointestinal & Antacids", sub: "Gastrointestinal Antibiotics", mfg: "Sun Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 360 },
    { name: "Mebeverine 135mg Tablet", salt: "Mebeverine Hydrochloride 135mg", brand: "Colospa 135", cat: "Gastrointestinal & Antacids", sub: "Irritable Bowel Syndrome (IBS)", mfg: "Abbott India", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 320 },
    { name: "Losartan 50mg Tablet", salt: "Losartan Potassium 50mg", brand: "Losar 50", cat: "Cardiovascular & Hypertension", sub: "Angiotensin Receptor Blockers (ARB)", mfg: "Unichem Labs", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 110 },
    { name: "Olmesartan 20mg Tablet", salt: "Olmesartan Medoxomil 20mg", brand: "Olmecip 20", cat: "Cardiovascular & Hypertension", sub: "Angiotensin Receptor Blockers (ARB)", mfg: "Cipla Ltd", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 145 },
    { name: "Nebivolol 5mg Tablet", salt: "Nebivolol Hydrochloride 5mg", brand: "Nebicard 5", cat: "Cardiovascular & Hypertension", sub: "Vasodilating Beta Blockers", mfg: "Torrent Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 125 },
    { name: "Cilnidipine 10mg Tablet", salt: "Cilnidipine 10mg", brand: "Cilacar 10", cat: "Cardiovascular & Hypertension", sub: "L/N Dual Calcium Blocker", mfg: "J.B. Chemicals", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 165 },
    { name: "Torsemide 10mg Tablet", salt: "Torsemide 10mg", brand: "Dytor 10", cat: "Cardiovascular & Hypertension", sub: "Loop Diuretics", mfg: "Cipla Ltd", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 95 },
    { name: "Spironolactone 25mg Tablet", salt: "Spironolactone 25mg", brand: "Aldactone 25", cat: "Cardiovascular & Hypertension", sub: "Potassium Sparing Diuretics", mfg: "RPG Life Sciences", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 68 },
    { name: "Vildagliptin 50mg Tablet", salt: "Vildagliptin 50mg", brand: "Galvus 50", cat: "Anti-Diabetic Care", sub: "DPP-4 Inhibitors", mfg: "Novartis India", rx: "Yes", type: "Tablet", count: 14, unit: "Sheet / Strip", p: 260 },
    { name: "Linagliptin 5mg Tablet", salt: "Linagliptin 5mg", brand: "Trajenta 5", cat: "Anti-Diabetic Care", sub: "DPP-4 Inhibitors", mfg: "Boehringer Ingelheim", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 490 },
    { name: "Pioglitazone 15mg Tablet", salt: "Pioglitazone 15mg", brand: "Pioz 15", cat: "Anti-Diabetic Care", sub: "Thiazolidinediones", mfg: "USV Ltd", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 75 },
    { name: "Voglibose 0.3mg Tablet", salt: "Voglibose 0.3mg", brand: "Volibo 0.3", cat: "Anti-Diabetic Care", sub: "Alpha-Glucosidase Inhibitors", mfg: "Sun Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 120 },
    { name: "Bilastine 20mg Tablet", salt: "Bilastine 20mg", brand: "Bilashine 20", cat: "Respiratory & Allergy", sub: "Antihistamines (2nd Gen)", mfg: "Sun Pharma", rx: "No", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 165 },
    { name: "Fexofenadine 120mg Tablet", salt: "Fexofenadine Hydrochloride 120mg", brand: "Allegra 120", cat: "Respiratory & Allergy", sub: "Antihistamines (Non-Drowsy)", mfg: "Sanofi India", rx: "No", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 185 },
    { name: "Deflazacort 6mg Tablet", salt: "Deflazacort 6mg", brand: "Defcort 6", cat: "Respiratory & Allergy", sub: "Glucocorticoids & Steroids", mfg: "Macleods Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 125 },
    { name: "Doxofylline 400mg Tablet", salt: "Doxofylline 400mg", brand: "Doxolin 400", cat: "Respiratory & Allergy", sub: "Xanthine Bronchodilators", mfg: "Zydus Cadila", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 135 },
    { name: "Levosulpiride 25mg Tablet", salt: "Levosulpiride 25mg", brand: "Lesuride 25", cat: "Neuro & Psychiatric", sub: "Atypical Antipsychotic & Prokinetic", mfg: "Sun Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 105 },
    { name: "Clonazepam 0.5mg Tablet", salt: "Clonazepam 0.5mg", brand: "Clona 0.5", cat: "Neuro & Psychiatric", sub: "Benzodiazepines", mfg: "Torrent Pharma", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 65 },
    { name: "Escitalopram 10mg Tablet", salt: "Escitalopram Oxalate 10mg", brand: "Nexito 10", cat: "Neuro & Psychiatric", sub: "SSRIs (Antidepressant)", mfg: "Sun Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 110 },
    { name: "Pregabalin 75mg Capsule", salt: "Pregabalin 75mg", brand: "Pregalin 75", cat: "Neuro & Psychiatric", sub: "Neuropathic Pain & GABA Analog", mfg: "Torrent Pharma", rx: "Yes", type: "Capsule", count: 15, unit: "Sheet / Strip", p: 235 },
    { name: "Gabapentin 300mg Tablet", salt: "Gabapentin 300mg", brand: "Gabapin 300", cat: "Neuro & Psychiatric", sub: "Neuropathic Pain & Anticonvulsants", mfg: "Intas Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 180 },
    { name: "Thyroxine Sodium 50mcg", salt: "Levothyroxine Sodium 50mcg", brand: "Thyronorm 50", cat: "Endocrinology & Thyroid", sub: "Thyroid Hormones", mfg: "Abbott India", rx: "Yes", type: "Tablet", count: 100, unit: "Bottle", p: 175 },
    { name: "Thyroxine Sodium 100mcg", salt: "Levothyroxine Sodium 100mcg", brand: "Eltroxin 100", cat: "Endocrinology & Thyroid", sub: "Thyroid Hormones", mfg: "GlaxoSmithKline", rx: "Yes", type: "Tablet", count: 100, unit: "Bottle", p: 195 },
    { name: "Zincovit Tablet", salt: "Multivitamin + Multimineral + Grape Seed Extract", brand: "Zincovit", cat: "Vitamins & Supplements", sub: "Multivitamin & Antioxidants", mfg: "Apex Laboratories", rx: "No", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 115 },
    { name: "Becadexamin Capsule", salt: "Vitamins A, D3, E, B-Complex with Zinc", brand: "Becadexamin", cat: "Vitamins & Supplements", sub: "Multivitamin & Minerals", mfg: "GlaxoSmithKline", rx: "No", type: "Capsule", count: 30, unit: "Bottle", p: 52 },
    { name: "Orofer-XT Tablet", salt: "Ferrous Ascorbate 100mg + Folic Acid 1.5mg", brand: "Orofer", cat: "Vitamins & Supplements", sub: "Hematinics & Iron Therapy", mfg: "Emcure Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 165 },
    { name: "Autrin Capsule", salt: "Ferrous Fumarate + Vitamin B12 + Folic Acid", brand: "Autrin", cat: "Vitamins & Supplements", sub: "Hematinics & Iron Therapy", mfg: "Pfizer India", rx: "No", type: "Capsule", count: 30, unit: "Bottle", p: 190 },
    { name: "Evion 400 Capsule", salt: "Tocopheryl Acetate (Vitamin E) 400mg", brand: "Evion", cat: "Vitamins & Supplements", sub: "Vitamin E & Skin Health", mfg: "Procter & Gamble", rx: "No", type: "Capsule", count: 10, unit: "Sheet / Strip", p: 38 },
    { name: "Tamsulosin 0.4mg Capsule", salt: "Tamsulosin Hydrochloride 0.4mg", brand: "Urimax 0.4", cat: "Urology & Nephrology", sub: "Alpha-1 Blockers (BPH)", mfg: "Cipla Ltd", rx: "Yes", type: "Capsule", count: 15, unit: "Sheet / Strip", p: 295 },
    { name: "Silodosin 8mg Capsule", salt: "Silodosin 8mg", brand: "Silofast 8", cat: "Urology & Nephrology", sub: "Alpha-1A Selective Blockers", mfg: "Cipla Ltd", rx: "Yes", type: "Capsule", count: 10, unit: "Sheet / Strip", p: 380 },
    { name: "Finasteride 5mg Tablet", salt: "Finasteride 5mg", brand: "Finast 5", cat: "Urology & Nephrology", sub: "5-Alpha Reductase Inhibitors", mfg: "Dr. Reddy's Labs", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 240 },
    { name: "Febuxostat 40mg Tablet", salt: "Febuxostat 40mg", brand: "Feburic 40", cat: "Orthopedics & Joint Care", sub: "Xanthine Oxidase Inhibitors (Gout)", mfg: "Sun Pharma", rx: "Yes", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 155 },
    { name: "Diacerein 50mg + Glucosamine 750mg", salt: "Diacerein 50mg + Glucosamine Sulfate 750mg", brand: "Cartigen Duo", cat: "Orthopedics & Joint Care", sub: "Cartilage & Joint Lubricants", mfg: "Pharmanova", rx: "No", type: "Tablet", count: 10, unit: "Sheet / Strip", p: 285 },
    { name: "Hydroxyzine 25mg Tablet", salt: "Hydroxyzine Hydrochloride 25mg", brand: "Atarax 25", cat: "Dermatology & Skin Care", sub: "Antihistamine & Pruritus", mfg: "Dr. Reddy's Labs", rx: "Yes", type: "Tablet", count: 15, unit: "Sheet / Strip", p: 92 },
    { name: "Permethrin 5% Lotion 60ml", salt: "Permethrin 5% w/v", brand: "Scaboma Lotion", cat: "Dermatology & Skin Care", sub: "Scabicides & Pediculicides", mfg: "Glenmark Pharma", rx: "No", type: "Syrup", count: 1, unit: "Bottle", p: 115 },
    { name: "Boric Acid Ear Drops 10ml", salt: "Boric Acid + Chlorbutol + Alcohol", brand: "Otogesic", cat: "Ophthalmic & ENT Care", sub: "Antiseptic Ear Drops", mfg: "East India Pharma", rx: "No", type: "Drops", count: 1, unit: "Bottle", p: 68 },
    { name: "Waxolve Ear Drops 10ml", salt: "Paradichlorobenzene + Benzocaine + Chlorbutol", brand: "Waxolve", cat: "Ophthalmic & ENT Care", sub: "Ear Wax Softeners", mfg: "Sun Pharma", rx: "No", type: "Drops", count: 1, unit: "Bottle", p: 95 },
  ];

  let saltIdx = 0;
  let batchCounter = 101;

  while (result.length < 200) {
    const s = saltBases[saltIdx % saltBases.length];
    const v = variations[result.length % variations.length];
    saltIdx++;
    batchCounter++;

    const packingCount = s.count || v.count || 10;
    const sheetPrice = +(s.p || v.sheetP).toFixed(2);
    const unitPrice = +(sheetPrice / packingCount).toFixed(2);
    const sheetCost = +(sheetPrice * 0.75).toFixed(2);
    const unitCost = +(sheetCost / packingCount).toFixed(2);

    result.push({
      "Medicine Name": `${s.brand} ${v.name}`,
      "Generic / Salt Name": s.salt,
      "Brand Name": s.brand,
      "Medicine Type": s.type,
      "Category": s.cat,
      "Sub Category": s.sub,
      "Manufacturer": s.mfg,
      "Prescription Required": s.rx,
      "Packing Count": packingCount,
      "Packaging Unit": s.unit || v.unit,
      "Sheet Price": sheetPrice,
      "Per Medicine Price": unitPrice,
      "Sheet Cost Price": sheetCost,
      "Per Medicine Cost Price": unitCost,
      "Full Sheets Stock": 20 + (result.length % 60),
      "Loose Units Stock": result.length % (packingCount > 1 ? packingCount - 1 : 1),
      "Batch Number": `BAT-${batchCounter}-2026`,
      "Expiry Date": `2028-0${(result.length % 9) + 1}-28`,
      "Description": `Clinical formulation of ${s.salt} manufactured by ${s.mfg}.`,
    });
  }

  return result.slice(0, 200);
}

// Download Sample 200 Medicines Excel File (.xlsx)
export function downloadSampleMedicinesExcel() {
  const data = getFull200MedicinesSample();
  const worksheet = XLSX.utils.json_to_sheet(data);

  // Set column widths for clean readability
  worksheet["!cols"] = [
    { wch: 30 }, // Medicine Name
    { wch: 45 }, // Generic / Salt Name
    { wch: 18 }, // Brand Name
    { wch: 14 }, // Medicine Type
    { wch: 28 }, // Category
    { wch: 28 }, // Sub Category
    { wch: 24 }, // Manufacturer
    { wch: 22 }, // Prescription Required
    { wch: 14 }, // Packing Count
    { wch: 18 }, // Packaging Unit
    { wch: 14 }, // Sheet Price
    { wch: 18 }, // Per Medicine Price
    { wch: 16 }, // Sheet Cost Price
    { wch: 22 }, // Per Medicine Cost Price
    { wch: 18 }, // Full Sheets Stock
    { wch: 18 }, // Loose Units Stock
    { wch: 18 }, // Batch Number
    { wch: 14 }, // Expiry Date
    { wch: 50 }, // Description
  ];

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "200 Medicines Sample");

  XLSX.writeFile(workbook, "PharmacyNext_Sample_Medicines_200.xlsx");
}

// Download Sample CSV
export function downloadSampleMedicinesCSV() {
  const data = getFull200MedicinesSample();
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csvOutput = XLSX.utils.sheet_to_csv(worksheet);

  const blob = new Blob([csvOutput], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", "PharmacyNext_Sample_Medicines_200.csv");
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
